### ISSUE TITLE
top page

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/orangesys.io#10]
@gaishimo 

top page
内容を流用します、css styleが新規サイトと合わせれば、OK
https://github.com/orangesys/orangesys.io#home-page

http://orangesys.io/

**Comment by gaishimo** [comment]
@gavinzhou これはログイン前のページ(LP)のことですか？

**Comment by gavinzhou** [comment]
はい、そうです。
説明してなかった、すみません。
top page、ログイン、決済ページ
3つの部分を出来た次第、0.1.0でリリースしようと考えてます。

**Comment by gavinzhou** [comment]
>```npm run build
cp -a src/lp target
>```
画像が表示となります。解消

**Comment by gavinzhou** [comment]
https://github.com/gavinzhou/vamp.io
でrenewしました。
