### ISSUE TITLE
Webpack production settings

### ISSUE THREAD

**Issue by gaishimo** [orangesys/orangesys.io#11]
現在development用しかない。

**Comment by gavinzhou** [comment]
本番運用につきまして、
build後、jsファイルとhtmlファイルだけでしょうか？
docker上で運用のため、webサーバが別のものに切り替え可能でしょうか？
@gaishimo

**Comment by gaishimo** [comment]
@gavinzhou はい、その予定です。

本番の場合はwebpack-devserverは使わずにwebpack-cliでstaticファイルをビルドする形になると思います。

**Comment by gaishimo** [comment]
done
