### ISSUE TITLE
Billing date on plans

### ISSUE THREAD

**Issue by gaishimo** [orangesys/orangesys.io#12]
@gavinzhou  プランの請求日は基本的に月初めになるんでしょうか？

デフォルトの場合、チャージ開始したその日が請求日になってしまうため、もしも1日にするのであれば`trial_end`を設定して調整する必要があります。

[Changing the Billing Cycle](https://stripe.com/docs/subscriptions/billing-cycle)

**Comment by gavinzhou** [comment]
@gaishimo 
月末締め、月初請求しようと思います。
最初、サービス開始日から、日割り（30日割）計算で考えてます。
exp)16日
(plan + options) / 30 * 利用日数 * SLA(default 1) = 請求額
(50 + 0) /30 *  16 * 1 ≒ 27 (四捨五入)

※javascripts Math.round

いかがでしょうか

**Comment by gaishimo** [comment]
@gavinzhou 

基本的にベースとなる月額の金額はPlanで決まっているため、日割りの場合はその金額に対して
マイナスのInvoiceアイテムを追加する形にしないといけないと思います。

以下は想定しているStripeのデータの流れです。

プラン50万、オプション5万、10/16日に登録した場合の例

### ユーザ登録・クレジットカード登録時

#### Customerデータ作成

```
{
  id: "cus_9KZ7SB7u58HIKM",
  email: "xxxx@example.com"
}
```

※customer_idはfirebaseのDBに保存しておく


#### Subscription作成

```
{
  id: "sub_9KZ50zVYFhdKww",
  customer_id: "cus_9KZ7SB7u58HIKM",
  plan: "largeプラン"",
  trial_end: 11/1
}
```

※trial_end: 11/1を設定しておくことで即時課金がされなくなる


#### Invoice Item

初回請求時の日割り分・オプション分をInvoice Itemとして追加しておく
※初回請求時はWebhook Eventが送られないため、このタイミングで追加しておく必要がある

```
{
  lines: [
    { invoice_item_id: xxxxxxx, amount:  500,000 },
    { invoice_item_id: xxxxxxx, amount:   50,000 },
    { invoice_item_id: xxxxxxx, amount: -274,995 },
  ],
  subtotal: 275,005
}
```

使ってない日数(日割りマイナス分): 15日 (11/1 - 11/15)
(500,000 + 50000) / 30 * 15 = 274,995

### 初回請求時 11/1

初回分 275,005が課金される


### 2回目請求時 12/1

Invoice作成後にWebhook Eventが送られる。

Invoiceに対してオプション分を追加する(1時間以内)

```
{
  lines: [
    { invoice_item_id: xxxxxxx, amount:  500,000 },
    { invoice_item_id: xxxxxxx, amount:   50,000 },
  ],
  subtotal: 550,000
}
```

Invoice作成1時間後に550,000が請求される

### 3回目以降 

2回目と同様。

### 解約時

subscriptionをcancelする。

`at_period_end: true` を指定すれば最後の請求まで行われる。
日割り計算が必要であれば行う。

**Comment by gavinzhou** [comment]
すみません
やはり、optionsの部分は日割りが不要にします。
計算式を訂正します。

**Comment by gavinzhou** [comment]
すみません、料金プランがやはり難しい
上記のやり方でいきましょ！！

**Comment by gaishimo** [comment]
@gavinzhou もう一つ細かい点なんですが、以下のようになりますか？

※オプション無しの場合
- 10月  1日に50,0000円のプランで登録 => 11月1日に500,000円請求
- 10月31日に50,0000円のプランで登録 => 11月1日に   16,667円請求

**Comment by gavinzhou** [comment]
ありがとうございます
この計算方法で行きましょ
月28、29、30、31日もあるから、全部のパータンを対応いただけると大変だと思います。
一括30日割にしましょ、良いサービスを作れば、この部分を気にしないと思います。

**Comment by gaishimo** [comment]
以下で日割り対応しました。
https://github.com/orangesys/orangesys.srv/pull/2
