### ISSUE TITLE
Add Sidebar

### ISSUE THREAD

**Issue by gaishimo** [orangesys/orangesys.io#23]
- Plan 表示
- Grafana ログイン情報を表示
- InfluxDB: tokenとインストール手順
- Logout

**Comment by gaishimo** [comment]
@gavinzhou Sidebarですが、こんなイメージでどうでしょうか？

<img width="961" alt="sidebar_example" src="https://cloud.githubusercontent.com/assets/4277693/20423009/26064c18-adb1-11e6-9ae6-9ef39c7623d8.png">

**Comment by gavinzhou** [comment]
LGTM
@gaishimo

**Comment by gaishimo** [comment]
@gavin 各メニューをクリックして画面を表示させたときに何を具体的に画面に表示させるか、もう一度教えていただけないでしょうか？(なんとなくは分かるんですがちょっと曖昧なので..)

**Comment by gavinzhou** [comment]
PLAN -> 基本のプラン表示
grafana -> grafanaのurlと初期ユーザー名とパスワード
influxdb -> influxdbのurl + jwt token、簡単のtelegrafインストール手順

これで大丈夫でしょうか

**Comment by gaishimo** [comment]
ありがとうございます 👍  OKです。

**Comment by gaishimo** [comment]
https://github.com/orangesys/orangesys.io/pull/32
