### ISSUE TITLE
change version by SemVer 2 

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/orangesys.io#4]
- [x] package.json
- [x] _VERSION

http://semver.org/

@gaishimo

**Comment by gaishimo** [comment]
@gavinzhou 
I've changed the version to 0.1.0.

https://github.com/orangesys/orangesys.io/commit/46ce0e90589cb0dddfc6732a58b14214258f240d
https://github.com/orangesys/orangesys.io/commit/b47b1db3afd58aa624e9ed55d9df997f86c14063
