### ISSUE TITLE
Price Plan

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/orangesys.io#6]
@gaishimo 

ユーザー登録時、料金プランを選び
カード認証登録、firebaseに下記の様な情報を保存します。

| 料金 | データ保存期間 | DB保存キーワード | ディスク容量 |
| --- | :-: | --: | --: |
| 5万/月 | 10日 | 10d | 10GB |
| 30万/月 | 40日 | 40d | 30GB |
| 50万/月 | 400日 | 400d | 100GB |

ex firebase table)
users
- companyName : aaa
- fullName: bbb
- priceplan: 10d

priceplan value is influxdb retetion policies.

https://docs.influxdata.com/influxdb/v1.0/query_language/database_management/#create-retention-policies-with-create-retention-policy

**Comment by gaishimo** [comment]
@gavinzhou 了解です 👍

**Comment by gaishimo** [comment]
@gavinzhou 
`10d`とか`40d'のIDはStripeでいうplanのIDになるんでしょうか？

<img width="726" alt="_test__plan_a001" src="https://cloud.githubusercontent.com/assets/4277693/19096304/4b2c1a84-8ad6-11e6-8c9c-4f830e2f5cff.png">

**Comment by gavinzhou** [comment]
10d、40dは

influxdb retetionの関数、10日の監視データを保存し、超過したら、自動削除する
```
CREATE RETENTION POLICY "one_day_only" ON "NOAA_water_database" DURATION 1d REPLICATION 1
```

**Comment by gaishimo** [comment]
@gavinzhou なるほど、planIDとは違いますね。

**Comment by gaishimo** [comment]
@gavinzhou Stripeで事前にPlanを登録しておく必要がありますが、フィールドでPlan IDが必要になります(文字列)。

もしもIDが決まったら教えて頂けますでしょうか。開発段階ではとりあえず仮のもので大丈夫ですが。


プランは以下のページから作成可能です。
https://dashboard.stripe.com/test/plans

<img width="993" alt="_test__plans" src="https://cloud.githubusercontent.com/assets/4277693/19144119/ce18093c-8be2-11e6-8918-cd1ca6aba202.png">

**Comment by gavinzhou** [comment]
@gaishimo 
わかりづらいなら、修正しでも構いません。
|PLAN ID|	COST|
|----------|:-------------:|
|400d|	¥500,000/month|
|40d|	¥300,000/month|
|10d	|¥50,000/month|

**Comment by gaishimo** [comment]
@gavinzhou 将来、あるプランの期間を変更したいみたいな可能性はないでしょうか？
たとえばplanAは最初10日だったが、15日に伸ばしたりしたいというようなケースです。
もしもその場合、PlanIDが期間を意味するものになっていると混乱するのではないかと思いました。

Lite, Standard, Proとか、Small, Medium, Largeとか、PlanA, PlanB, PlanCとか、内容を含まない感じするといいと思うのですがどうでしょうか?

**Comment by gavinzhou** [comment]
@gaishimo 
更新しました

**Comment by gaishimo** [comment]
TODO: ディスク容量を表示する

**Comment by gaishimo** [comment]
https://github.com/orangesys/orangesys.io/pull/28
