### ISSUE TITLE
get token form backend api

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/orangesys.io#7]
@gaishimo 

ユーザー登録後（カード認証済み状態）、環境は自動構築
backend apiをたたく、telegraf用のtokenを返してくる
firebaseに保存（readonly）、user dashboardに表示します。

[fake-jwt-token-api](https://github.com/orangesys/fake-jwt-token-api)

jsonデータを返す、そのままで、firebaseに保存で良いかな、
確認をお願い致します。

PS
```
telegraf.conf
urls = ["https://pqaxel.i.orangesys.io/?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2OTA1MmI0ZWMzODk0ZjZiOWJiM2Q0ZGE2NDg0ZGQ3NiJ9.9dEvXPYp7IhRjexFfBWR5uBMOoR0U7tJdBh-f4Fwxdw"]
```
```
grafana URL
https://pqaxel.g.orangesys.io
```

「pqaxel」6 lower alphabet rule

- [x] firebase user tables modify

**Comment by gaishimo** [comment]
はい、問題ないと思います。

**Comment by gavinzhou** [comment]
API変更可能性があります、
ユーザー登録時のdataflowを作成します。

**Comment by gavinzhou** [comment]
@gaishimo 

ユーザー登録のprocess flow chartが下記となりますが、いかがでしょうか
- helmとはkuberenetes構築ツール
- ユーザー登録確認後、helmへアクセスし、consumers_id(6文字の小文字アルファベット)をGETします。
- KONG(apigateway)へGET http://<internal server>/consumers/hgrfgfへアクセスすると、tokenをGETします。

わかりづらいなら、ご指摘ください

![usersingup](http://g.gravizo.com/g?
 digraph G {
   usersingup -> { firebase; stripe}
   usersingup -> helm;
   helm -> usersingup [style=bold, label="response consumer_id"];
   kong -> usersingup [style=bold, label="response consumer_id:token"];
   helm -> kong;
   helm -> grafana;
   helm -> influxdb;
 }
)

**Comment by gaishimo** [comment]
@
gavin 
> helmへアクセス

というのは具体的にどうやってアクセスするんでしょうか？

**Comment by gavinzhou** [comment]
この感じかなぁ

```
GET http://<helm api>/<priceplan>
```

exp)40日 plan
```
http http://helm.apigateway/40d

```

**Comment by gaishimo** [comment]
なるほど、普通にAPIでHTTPリクエストを送る感じですね。

**Comment by gavinzhou** [comment]
fake-jwt-token-apiを修正します。
分かりやすいかも

**Comment by gavinzhou** [comment]
@gaishimo 
[fake-jwt-token-api](https://github.com/orangesys/fake-jwt-token-api)
を修正しました。

ご確認をお願い致します。

**Comment by gavinzhou** [comment]
@gaishimo 
すみません、やはりAPIの仕様がまだ変わるかもしれない
この部分開発が最後にしましょ
いずれに、GET URL/?query=stringで、json dataを返し、そのままでfirebaseに保存のやり方が変わらないです。

**Comment by gaishimo** [comment]
了解です 👍

**Comment by gavinzhou** [comment]
@gaishimo 

[fake-jwt-token-api](https://github.com/orangesys/fake-jwt-token-api)

バタバタしましたが、一旦fixしました。
テストをお願い致します。

ユーザー登録後、backend apiを叩き、reponse内容をfirebaseにそのままで保存します。
保存内容はユーザーログイン後、ページに表示する予定です。

**Comment by gaishimo** [comment]
https://github.com/orangesys/orangesys.io/pull/18
